language: python
python:
  - "3.6"
  - "3.7-dev"
before_install:
  - python --version
  - uname -a
  - lsb_release -a 
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test --cov-report term --cov=tests/
env:
  - CODECOV_TOKEN="0d56028c-9cfd-4536-964a-5151c4115d3d"
after_success:
  - codecov