dist: xenial
language: python
python: 3.7
sudo: required
services: xvfb
before_install:
  - python --version
  - uname -a
  - lsb_release -a 
  - sudo apt-get install -y xvfb herbstluftwm dzen2
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 5
  - pip install -r requirements.txt

# command to run tests
before_script:
  - "herbstluftwm &"
  - sleep 5
script:
  - py.test --cov-report term --cov=src/
env:
  - CODECOV_TOKEN="0d56028c-9cfd-4536-964a-5151c4115d3d"
after_success:
  - codecov

